sudo: false
language: node_js
node_js: [ 8, 10, "node", "lts/*" ]

before_install: npm i -g npm@latest

install: travis_retry npm install

script: npm run coverage

after_success: npm run report-coverage