sudo: false
language: node_js
node_js: [ 8, 10, "node", "lts/*" ]

before_install: npm i -g npm@latest

install: travis_retry npm install

script:
  - if [ $TRAVIS_EVENT_TYPE == 'cron' ];
    then npm run integration-test;
    else npm run coverage;
    fi;

after_success: 
  - if [ $TRAVIS_EVENT_TYPE != 'cron' ];
    then npm run report-coverage; 
    fi;
