name:  Integration test

on: [ 'push' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        node_version: [ '16' ]
        architecture: [ 'x64' ]
    name: Node ${{ matrix.node_version }}_${{ matrix.architecture }} on ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          
      - name: Install dependencies
        run: npm install
        
      - name: Run integration test
        run: npm run integration-test

      - name: Register coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
          flag-name: Node ${{ matrix.node_version }}_${{ matrix.architecture }} on ${{ matrix.os }}
          parallel: true

  report-coverage:
    name: Summarize and report coverage

    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Report coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ github.token }}
        parallel-finished: true
