name: Unit testing

on: [ 'push', 'pull_request', 'workflow_dispatch' ]

jobs:
  test-and-report-coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        node_version: [ '12', '14', '16' ]
        architecture: [ 'x64' ]
    name: Node ${{ matrix.node_version }}_${{ matrix.architecture }} on ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          
      - name: Install dependencies
        run: npm install
        
      - name: Test code, generate coverage report
        run: npm run coverage

      - name: Report coverage to Coveralls
        run: npm run report-coverage
